### ISSUE TITLE
Owning a home live???

### ISSUE THREAD

**Issue by Ooblioob** [cfpb/owning-a-home#297]
We did it!! 
![selfie-0](http://i.imgur.com/X6E428i.gif)

**Comment by mistergone** [comment]
Site launch or touchdown? :football: :question:

**Comment by mthibos** [comment]
I'm trying to join the dance party but it's not working  :sob: 

But this is so exciiiiiiittttttiiiiinnngggggg!!!!  :grinning: :dancer: :rocket:

**Comment by rosskarchner** [comment]
Good work, all!

**Comment by mebates** [comment]
so aggressive! #testosterone


![selfie-0](http://i.imgur.com/ucplpE3.gif)

**Comment by dezzie** [comment]
![selfie-0](http://i.imgur.com/GAiwsed.gif)

**Comment by Ooblioob** [comment]
Ok, I'm closing down this silliness.

**Comment by mistergone** [comment]
![shut it down](http://www.reactiongifs.com/wp-content/uploads/2013/01/shut-it-down.gif)

**Comment by mebates** [comment]
![selfie-0](http://i.imgur.com/WZpinTW.gif)

**Comment by marcesher** [comment]
Congrats, everyone!

![selfie-0](http://i.imgur.com/JJjZrhl.gif)
