### ISSUE TITLE
Getting an error about 'debounce' when trying to run the site locally for the first time

### ISSUE THREAD

**Issue by himedlooff** [cfpb/owning-a-home#305]
When running `grunt build` after `grunt vendor`, I receive the following error:

```
Running "browserify:build" (browserify) task
>> Error: Cannot find module 'debounce' from '/code/owning-a-home/src/static/js/modules'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

**Comment by mistergone** [comment]
I thought I had checked that no code was using debounce anymore, but I was wrong. :sob: :rocket: :dancer: 

This is fixed in https://github.com/cfpb/owning-a-home/pull/306

**Comment by mistergone** [comment]
@himedlooff - If you don't mind, can you check this again and close the issue if you're satisfied? :dancer: :dancer: :dancer: :rocket: :rabbit:

**Comment by himedlooff** [comment]
Works, thanks!
