### ISSUE TITLE
In Readme, consider naming virtualenv `OAH`

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/owning-a-home#311]
Based on a discussion with @ascott1, consider renaming the virtualenv in the project Readme to `OAH` instead of `sheer` to better align the public instructions of the project with the internal instructions:

So:

```
$ mkvirtualenv sheer
```

Would become:

```
$ mkvirtualenv OAH
```

**Comment by ascott1** [comment]
I think this makes a lot of sense as it would line up the README with our internal documentation.
