### ISSUE TITLE
`jquery.scrollto` cannot be found

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/owning-a-home#326]
I'm getting this error on master when running `grunt vendor` followed by `grunt`:

```
>> Error: Cannot find module 'jquery.scrollto'
```

**Comment by jimmynotjim** [comment]
Shouldn't that be `jquery.scrollTo`?

**Comment by himedlooff** [comment]
So, some JS is brought in through NPM. JS brought in this way plays nicer with Browserify. You should run `npm install` to make sure you have it. I bet it can't find it because you haven't ran that in a while.

**Comment by anselmbradford** [comment]
yep, `npm install` solved it :)
