### ISSUE TITLE
What does this homepage JS do?

### ISSUE THREAD

**Issue by cfarm** [cfpb/owning-a-home#369]
@ascott1 @contolini @mistergone 
Why is this JS at the bottom of the homepage?

https://github.com/cfpb/owning-a-home/blob/master/src/index.html#L110

I thought maybe some JavaScript is dependent on it, since otherwise it could just be added using Jekyll, but found no references to the class name "index" outside of the CSS files.

**Comment by contolini** [comment]
ping @akiany

**Comment by cfarm** [comment]
Removed this JS in https://github.com/cfpb/owning-a-home/pull/378
