### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by amymok** [cfpb/owning-a-home#433]
This only seem to happen if it reaches to 10 or more lenders.

![screen shot 2015-05-13 at 1 00 18 pm](https://cloud.githubusercontent.com/assets/2673022/7616134/4891e50e-f970-11e4-9eee-984075d2dddf.png)

**Comment by mthibos** [comment]
Right you are, @amymok, this happens when the lenders are in the 2 digits.  This is on our backlog to fix, but way down at the forgotten bottom.  Perhaps @cfarm this could be a candidate for "needs help" from the broader public?

**Comment by stephanieosan** [comment]
For more context, this can be found at www.consumerfinance.gov/owning-a-home/check-rates

**Comment by jnsnkrllive** [comment]
This does not appear to be an issue anymore. Here is a screenshot from today where there are double-digit lenders for a rate and the text is not overlapping.
![2016_11_10_08_57_26_owning_a_home_explore_interest_rates_consumer_financial_protection_bureau](https://cloud.githubusercontent.com/assets/6225628/20186232/03d6928a-a724-11e6-8711-f4b9d8a742e2.png)

**Comment by KimberlyMunoz** [comment]
Thanks for checking @jnsnkrllive! I'll close this issue and we can reopen if we see it happening again.
