### ISSUE TITLE
Can't submit pull request for PDF

### ISSUE THREAD

**Issue by kmcurry** [cfpb/owning-a-home#695]
I would like to submit a pull request for content linked on the site but the content is a PDF.

http://www.consumerfinance.gov/owning-a-home/resources/checklist_mortgage_closing.pdf

**Comment by Scotchester** [comment]
@mthibos might be able to speak more to the origin and purpose of this document, but what kinds of changes would you like to propose? If you list them here, we can take them into consideration.

**Comment by kmcurry** [comment]
I was going to suggest "Evidence of Insurance" as a checklist item under "3. Request your closing
documents three days in advance of closing."

But I think now it doesn't belong because it can be assumed if the Mortgage item is complete. A loan officer should have already verified evidence of insurance.
